import {
  Clinic,
  StaffUser,
  Customer,
  Pet,
  PetMedicalRecord,
  ServiceItem,
  Appointment,
  SubscriptionPlan,
  CustomerSubscription,
  InventoryItem,
  Invoice,
  NotificationLog
} from '@/types/database';

export const INITIAL_CLINIC: Clinic = {
  id: 'c101',
  name: 'Petia - Vila Madalena',
  slug: 'petia-vila-madalena',
  phone: '(11) 98765-4321',
  address: 'Rua Harmonia, 450 - Vila Madalena, São Paulo - SP',
  logo_url: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=150&auto=format&fit=crop&q=80',
  plan: 'pro',
  created_at: new Date().toISOString(),
};

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'u1',
    clinic_id: 'c101',
    name: 'Dr. Lucas Mendes',
    role: 'vet',
    email: 'lucas@petia.com.br',
    created_at: new Date().toISOString(),
  },
  {
    id: 'u2',
    clinic_id: 'c101',
    name: 'Dra. Camila Rocha',
    role: 'vet',
    email: 'camila@petia.com.br',
    created_at: new Date().toISOString(),
  },
  {
    id: 'u3',
    clinic_id: 'c101',
    name: 'Ana Beatris (Recepção)',
    role: 'attendant',
    email: 'ana@petia.com.br',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    clinic_id: 'c101',
    name: 'Mariana Silva Santos',
    phone: '(11) 99123-4567',
    email: 'mariana.silva@email.com',
    whatsapp_opt_in: true,
    created_at: '2026-01-15T10:00:00Z',
    pets_count: 2,
  },
  {
    id: 'cust-2',
    clinic_id: 'c101',
    name: 'Carlos Eduardo Oliveira',
    phone: '(11) 98877-6655',
    email: 'carlos.edu@email.com',
    whatsapp_opt_in: true,
    created_at: '2026-02-01T14:30:00Z',
    pets_count: 1,
  },
  {
    id: 'cust-3',
    clinic_id: 'c101',
    name: 'Fernanda Lima Castro',
    phone: '(11) 97766-5544',
    email: 'nanda.lima@email.com',
    whatsapp_opt_in: true,
    created_at: '2026-03-10T11:20:00Z',
    pets_count: 1,
  },
  {
    id: 'cust-4',
    clinic_id: 'c101',
    name: 'Roberto Souza Jr.',
    phone: '(11) 96543-2109',
    email: 'roberto.souza@email.com',
    whatsapp_opt_in: false,
    created_at: '2026-04-05T16:00:00Z',
    pets_count: 1,
  },
];

export const INITIAL_PETS: Pet[] = [
  {
    id: 'pet-1',
    clinic_id: 'c101',
    customer_id: 'cust-1',
    customer_name: 'Mariana Silva Santos',
    name: 'Thor',
    species: 'Cão',
    breed: 'Golden Retriever',
    birth_date: '2022-05-12',
    weight: 31.5,
    sex: 'M',
    neutered: true,
    photo_url: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=300&auto=format&fit=crop&q=80',
    notes: 'Alegre, adora água, sensível ao secador de cabelo.',
    created_at: '2026-01-15T10:05:00Z',
  },
  {
    id: 'pet-2',
    clinic_id: 'c101',
    customer_id: 'cust-1',
    customer_name: 'Mariana Silva Santos',
    name: 'Luna',
    species: 'Gato',
    breed: 'Persa Siamês',
    birth_date: '2023-08-20',
    weight: 4.2,
    sex: 'F',
    neutered: true,
    photo_url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300&auto=format&fit=crop&q=80',
    notes: 'Sensível a ruídos fortes. Manusear com cuidado.',
    created_at: '2026-01-15T10:10:00Z',
  },
  {
    id: 'pet-3',
    clinic_id: 'c101',
    customer_id: 'cust-2',
    customer_name: 'Carlos Eduardo Oliveira',
    name: 'Bob',
    species: 'Cão',
    breed: 'Bulldog Francês',
    birth_date: '2021-11-03',
    weight: 12.8,
    sex: 'M',
    neutered: true,
    photo_url: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format&fit=crop&q=80',
    notes: 'Acompanhamento dermatológico. Usar shampoo hipoalergênico.',
    created_at: '2026-02-01T14:35:00Z',
  },
  {
    id: 'pet-4',
    clinic_id: 'c101',
    customer_id: 'cust-3',
    customer_name: 'Fernanda Lima Castro',
    name: 'Mel',
    species: 'Cão',
    breed: 'Shih Tzu',
    birth_date: '2024-01-10',
    weight: 5.8,
    sex: 'F',
    neutered: false,
    photo_url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=300&auto=format&fit=crop&q=80',
    notes: 'Assinante do Plano Banho Semanal.',
    created_at: '2026-03-10T11:25:00Z',
  },
];

export const INITIAL_MEDICAL_RECORDS: PetMedicalRecord[] = [
  {
    id: 'med-1',
    pet_id: 'pet-1',
    type: 'vaccine',
    description: 'Vacina Óctupla V10 (Reforço Anual Importada)',
    date: '2026-02-10',
    next_due_date: '2027-02-10',
    vet_id: 'u1',
    vet_name: 'Dr. Lucas Mendes',
    created_at: '2026-02-10T11:00:00Z',
  },
  {
    id: 'med-2',
    pet_id: 'pet-1',
    type: 'deworming',
    description: 'Vermífugo Drontal Plus (Comprimido 35kg)',
    date: '2026-05-15',
    next_due_date: '2026-08-15',
    vet_id: 'u1',
    vet_name: 'Dr. Lucas Mendes',
    created_at: '2026-05-15T10:30:00Z',
  },
  {
    id: 'med-3',
    pet_id: 'pet-2',
    type: 'vaccine',
    description: 'Vacina Quádrupla Felina V4',
    date: '2026-03-01',
    next_due_date: '2026-09-01',
    vet_id: 'u2',
    vet_name: 'Dra. Camila Rocha',
    created_at: '2026-03-01T14:00:00Z',
  },
  {
    id: 'med-4',
    pet_id: 'pet-3',
    type: 'consultation',
    description: 'Consulta Dermatológica - Avaliação de dermatite atópica',
    date: '2026-07-20',
    vet_id: 'u2',
    vet_name: 'Dra. Camila Rocha',
    created_at: '2026-07-20T16:00:00Z',
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    clinic_id: 'c101',
    name: 'Banho & Tosa Completa (Porte Grande)',
    category: 'banho',
    price: 130.00,
    duration_minutes: 60,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'srv-2',
    clinic_id: 'c101',
    name: 'Banho Higiênico (Porte Pequeno/Médio)',
    category: 'banho',
    price: 75.00,
    duration_minutes: 45,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'srv-3',
    clinic_id: 'c101',
    name: 'Consulta Clínica Veterinária',
    category: 'consulta',
    price: 180.00,
    duration_minutes: 30,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'srv-4',
    clinic_id: 'c101',
    name: 'Aplicação de Vacina Importada (V10/V4)',
    category: 'vacina',
    price: 110.00,
    duration_minutes: 20,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'srv-5',
    clinic_id: 'c101',
    name: 'Tosa Higiênica + Corte de Unhas',
    category: 'tosa',
    price: 50.00,
    duration_minutes: 30,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'srv-6',
    clinic_id: 'c101',
    name: 'Procedimento de Castração (Cão/Gato)',
    category: 'cirurgia',
    price: 650.00,
    duration_minutes: 120,
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    clinic_id: 'c101',
    pet_id: 'pet-1',
    pet_name: 'Thor (Golden)',
    customer_id: 'cust-1',
    customer_name: 'Mariana Silva Santos',
    customer_phone: '(11) 99123-4567',
    service_type: 'Banho & Tosa Completa (Porte Grande)',
    staff_id: 'u3',
    staff_name: 'Ana Beatris (Recepção)',
    scheduled_at: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    duration_minutes: 60,
    status: 'confirmed',
    price: 130.00,
    notes: 'Tutor solicitou hidratação de pelos.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-2',
    clinic_id: 'c101',
    pet_id: 'pet-3',
    pet_name: 'Bob (Bulldog)',
    customer_id: 'cust-2',
    customer_name: 'Carlos Eduardo Oliveira',
    customer_phone: '(11) 98877-6655',
    service_type: 'Consulta Clínica Veterinária',
    staff_id: 'u1',
    staff_name: 'Dr. Lucas Mendes',
    scheduled_at: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
    duration_minutes: 30,
    status: 'scheduled',
    price: 180.00,
    notes: 'Retorno dermatológico.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-3',
    clinic_id: 'c101',
    pet_id: 'pet-4',
    pet_name: 'Mel (Shih Tzu)',
    customer_id: 'cust-3',
    customer_name: 'Fernanda Lima Castro',
    customer_phone: '(11) 97766-5544',
    service_type: 'Banho Higiênico (Porte Pequeno/Médio)',
    staff_id: 'u3',
    staff_name: 'Ana Beatris (Recepção)',
    scheduled_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    duration_minutes: 45,
    status: 'done',
    price: 75.00,
    notes: 'Atendimento concluído com sucesso.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt-4',
    clinic_id: 'c101',
    pet_id: 'pet-2',
    pet_name: 'Luna (Gato Persa)',
    customer_id: 'cust-1',
    customer_name: 'Mariana Silva Santos',
    customer_phone: '(11) 99123-4567',
    service_type: 'Aplicação de Vacina Importada (V10/V4)',
    staff_id: 'u2',
    staff_name: 'Dra. Camila Rocha',
    scheduled_at: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    duration_minutes: 20,
    status: 'scheduled',
    price: 110.00,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-1',
    clinic_id: 'c101',
    name: 'Plano Banho VIP Mensal (4 Banhos/mês)',
    price: 240.00,
    frequency: 'mensal',
    services_included: ['4x Banhos Higiênicos', '1x Tosa Higiênica', 'Corte de Unhas ilimitado'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'plan-2',
    clinic_id: 'c101',
    name: 'Plano Saúde Pet Total',
    price: 189.00,
    frequency: 'mensal',
    services_included: ['Consultas clínicas ilimitadas', 'Vacinas anuais inclusas', '15% de desconto em cirurgias'],
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_CUSTOMER_SUBSCRIPTIONS: CustomerSubscription[] = [
  {
    id: 'sub-1',
    customer_id: 'cust-3',
    customer_name: 'Fernanda Lima Castro (Pet: Mel)',
    plan_id: 'plan-1',
    plan_name: 'Plano Banho VIP Mensal',
    stripe_subscription_id: 'sub_1QkL99827361',
    status: 'active',
    current_period_end: new Date(Date.now() + 1000 * 60 * 60 * 24 * 18).toISOString(),
    created_at: '2026-03-10T00:00:00Z',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    clinic_id: 'c101',
    name: 'Shampoo Hipoalergênico Pelos Claros 5L',
    category: 'Estética',
    quantity: 3,
    min_quantity: 5,
    unit_cost: 145.00,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-2',
    clinic_id: 'c101',
    name: 'Vacina V10 Zoetis (Frasco 1 dose)',
    category: 'Medicamentos',
    quantity: 18,
    min_quantity: 10,
    unit_cost: 38.50,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-3',
    clinic_id: 'c101',
    name: 'Vermífugo Drontal Plus 35kg (Caixa c/ 2 comp)',
    category: 'Medicamentos',
    quantity: 2,
    min_quantity: 6,
    unit_cost: 42.00,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-4',
    clinic_id: 'c101',
    name: 'Laços e Gravatas Sortidas (Pacote c/ 50)',
    category: 'Acessórios',
    quantity: 120,
    min_quantity: 30,
    unit_cost: 0.85,
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'invc-101',
    clinic_id: 'c101',
    customer_id: 'cust-3',
    customer_name: 'Fernanda Lima Castro',
    appointment_id: 'apt-3',
    amount: 75.00,
    status: 'paid',
    stripe_payment_id: 'pi_3Mqv9987',
    paid_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'invc-102',
    clinic_id: 'c101',
    customer_id: 'cust-1',
    customer_name: 'Mariana Silva Santos',
    appointment_id: 'apt-1',
    amount: 130.00,
    status: 'pending',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_NOTIFICATION_LOGS: NotificationLog[] = [
  {
    id: 'log-1',
    clinic_id: 'c101',
    customer_id: 'cust-1',
    customer_name: 'Mariana Silva Santos',
    channel: 'whatsapp',
    type: 'Lembrete Agendamento (24h)',
    sent_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    status: 'delivered',
  },
  {
    id: 'log-2',
    clinic_id: 'c101',
    customer_id: 'cust-2',
    customer_name: 'Carlos Eduardo Oliveira',
    channel: 'email',
    type: 'Alerta Vacina Vencendo (Luna)',
    sent_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    status: 'delivered',
  },
];
